#!/usr/bin/with-contenv sh

echo "[init] 设置 PUID/PGID..."
groupmod -o -g $PGID transmission || true
usermod -o -u $PUID transmission || true

echo "[init] 修复权限..."
chown -R $PUID:$PGID /config /downloads

echo "[init] 确保 settings.json 存在..."
if [ ! -f /config/settings.json ]; then
    echo "{}" > /config/settings.json
fi
